// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.infy.entities;

import com.infy.entities.AntDirectory;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect AntDirectory_Roo_Configurable {
    
    declare @type: AntDirectory: @Configurable;
    
}
